// Vous devez compléter ce fichier
@startuml
skinparam style strictuml
skinparam packageStyle rect
skinparam defaultfontname Verdana

title DSS pour le scénario <i>Redémarrer</i>

actor ":Joueur" as J
participant ":Système" as S

J -> S: redémarrerJeu()
@enduml